new(CI): add docker image workflow
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -5,19 +5,19 @@ ARG RELEASE
 ARG COMMIT
 ARG BUILD_DATE
 ARG PROJECT=github.com/falcosecurity/falco-operator
-ARG OPERATOR
+ARG COMPONENT
 
 RUN test -n "$RELEASE" || ( echo "The RELEASE argument is unset. Aborting" && false )
 RUN test -n "$COMMIT" || ( echo "The COMMIT argument is unset. Aborting" && false )
 RUN test -n "$BUILD_DATE" || ( echo "The BUILD_DATE argument is unset. Aborting" && false )
-RUN test -n "$OPERATOR" || ( echo "The OPERATOR argument is unset. Aborting" && false )
+RUN test -n "$COMPONENT" || ( echo "The COMPONENT argument is unset. Aborting" && false )
 
 COPY go.mod ./go.mod
 COPY go.sum ./go.sum
 RUN  go mod download
 
 # Copy the go source
-COPY cmd/${OPERATOR}/main.go cmd/${OPERATOR}/main.go
+COPY cmd/${COMPONENT}/main.go cmd/${COMPONENT}/main.go
 COPY api/ api/
 COPY internal/ internal/
 
@@ -30,15 +30,15 @@ RUN CGO_ENABLED=0 \
     -X '${PROJECT}/internal/pkg/version.SemVersion=${RELEASE}' \
     -X '${PROJECT}/internal/pkg/version.GitCommit=${COMMIT}' \
     -X '${PROJECT}/internal/pkg/version.BuildDate=${BUILD_DATE}'" \
-    -o ${OPERATOR} ./cmd/${OPERATOR}/main.go
+    -o ${COMPONENT} ./cmd/${COMPONENT}/main.go
 
 RUN echo ${RELEASE}
 
 FROM cgr.dev/chainguard/static:latest
 
-ARG OPERATOR
+ARG COMPONENT
 
-COPY --from=builder /tmp/builder/${OPERATOR} /usr/bin/manager
+COPY --from=builder /tmp/builder/${COMPONENT} /usr/bin/manager
 USER 65532:65532
 
 ENTRYPOINT [ "/usr/bin/manager" ]
