new(Dockerfile): add Dockerfile for both operators
A single Dockerfile that allows building falco and artifact operators.

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -5,16 +5,21 @@ ARG RELEASE
 ARG COMMIT
 ARG BUILD_DATE
 ARG PROJECT=github.com/alacuku/falco-operator
+ARG OPERATOR
 
 RUN test -n "$RELEASE" || ( echo "The RELEASE argument is unset. Aborting" && false )
 RUN test -n "$COMMIT" || ( echo "The COMMIT argument is unset. Aborting" && false )
 RUN test -n "$BUILD_DATE" || ( echo "The BUILD_DATE argument is unset. Aborting" && false )
+RUN test -n "$OPERATOR" || ( echo "The OPERATOR argument is unset. Aborting" && false )
 
 COPY go.mod ./go.mod
 COPY go.sum ./go.sum
 RUN  go mod download
 
-COPY . ./
+# Copy the go source
+COPY cmd/${OPERATOR}/main.go cmd/${OPERATOR}/main.go
+COPY api/ api/
+COPY internal/ internal/
 
 RUN CGO_ENABLED=0 \
     GOOS=$(go env GOOS) \
@@ -22,15 +27,18 @@ RUN CGO_ENABLED=0 \
     go build -ldflags \
     "-s \
     -w \
-    -X '${PROJECT}/cmd/sidecar/main.semVersion=${RELEASE}' \
-    -X '${PROJECT}/cmd/sidecar/main.gitCommit=${COMMIT}' \
-    -X '${PROJECT}/cmd/sidecar/main.buildDate=${BUILD_DATE}'" \
-    ./cmd/sidecar/main.go
+    -X '${PROJECT}/internal/pkg/version.SemVersion=${RELEASE}' \
+    -X '${PROJECT}/internal/pkg/version.GitCommit=${COMMIT}' \
+    -X '${PROJECT}/internal/pkg/version.BuildDate=${BUILD_DATE}'" \
+    -o ${OPERATOR} ./cmd/${OPERATOR}/main.go
 
 RUN echo ${RELEASE}
 
 FROM cgr.dev/chainguard/static:latest
 
-COPY --from=builder /tmp/builder/sidecar /usr/bin/sidecar
+ARG OPERATOR
 
-ENTRYPOINT [ "/usr/bin/sidecar" ]
+COPY --from=builder /tmp/builder/${OPERATOR} /usr/bin/manager
+USER 65532:65532
+
+ENTRYPOINT [ "/usr/bin/manager" ]
